[project]
name = "lcblm"
version = "0.1.0"
description = "Leanable Concept-Based Language Model"
readme = "README.md"
authors = [
    { name = "Francesco Marchisotti", email = "francesco.marchisotti@gmail.com" },
]
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "numpy<2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "numpy; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "torch==2.2.2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "torch; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "matplotlib>=3.10.7",
    "trainvox @ git+http://github.com/marchfra/trainvox",
    "transformers>=4.57.3",
    "python-dotenv>=1.2.1",
    "better-kaggle-secrets @ git+https://github.com/marchfra/better-kaggle-secrets",
    "datasets>=4.4.1",
    "pydantic>=2.12.5",
    "evaluate>=0.4.6",
    "geom-median>=0.1.0",
]

[tool.uv.sources]
trainvox = { git = "http://github.com/marchfra/trainvox" }
better-kaggle-secrets = { git = "https://github.com/marchfra/better-kaggle-secrets" }

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
breaking_change_exclamation_in_title = true

[tool.ruff]
extend = "~/.config/ruff/ruff.toml"

[tool.ruff.lint.per-file-ignores]
"src/lcblm/scripts/*.py" = ["E402", "E501", "N999"]

[tool.pyright]
exclude = [".venv"]
venvPath = "."
venv = ".venv"

[tool.jupytext.formats]
"notebooks/" = "ipynb"
"scripts/" = "py:percent"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.10.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupytext>=1.18.1",
    "pre-commit>=4.5.0",
]
