[project]
name = "lcblm"
version = "0.1.0"
description = "Leanable Concept-Based Language Model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy<2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "numpy; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "torch==2.2.2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "torch; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "matplotlib>=3.10.7",
    "trainvox",
    "sae-utils",
    "transformers>=4.57.3",
    "python-dotenv>=1.2.1",
]

[tool.uv.sources]
trainvox = { git = "http://github.com/marchfra/trainvox" }
sae-utils = { git = "https://github.com/marchfra/sae-utils.git" }

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
breaking_change_exclamation_in_title = true

[project.scripts]
lcblm = "lcblm:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["commitizen>=4.10.0", "pre-commit>=4.5.0"]
