[project]
name = "lcblm"
version = "0.1.0"
description = "Leanable Concept-Based Language Model"
readme = "README.md"
authors = [
    { name = "Francesco Marchisotti", email = "francesco.marchisotti@gmail.com" },
]
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "numpy<2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "numpy; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "torch==2.2.2; sys_platform == 'darwin' and platform_machine != 'arm64'",
    "torch==2.8.0; sys_platform != 'darwin' or platform_machine == 'arm64'",
    "matplotlib==3.10.8",
    "trainvox @ git+http://github.com/marchfra/trainvox",
    "transformers==5.1.0",
    "python-dotenv==1.2.1",
    "better-kaggle-secrets @ git+https://github.com/marchfra/better-kaggle-secrets",
    "datasets==4.5.0",
    "pydantic>=2.12.5",
    "evaluate==0.4.6",
    "geom-median>=0.1.0",
    "huggingface-hub==1.4.1",
    "scikit-learn>=1.8.0",
]

[project.scripts]
embae-exp = "experiments.embae_comparison.exp_cli:main"
vaee-exp = "experiments.vaee_vs_sae.exp_cli:main"

[dependency-groups]
dev = [
    "commitizen>=4.10.0",
    "jupytext>=1.18.1",
    "pre-commit>=4.5.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.uv.sources]
trainvox = { git = "http://github.com/marchfra/trainvox" }
better-kaggle-secrets = { git = "https://github.com/marchfra/better-kaggle-secrets" }
torch = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
breaking_change_exclamation_in_title = true

[tool.pytest.ini_options]
addopts = "-ra -q --cov=lcblm --cov-report=html"
testpaths = ["tests"]

[tool.ruff]
extend = "~/.config/ruff/ruff.toml"
extend-exclude = ["experiments/embae_comparison/embae_diagnosis.py"]

[tool.ruff.lint.per-file-ignores]
"src/lcblm/scripts/*.py" = ["E402", "E501", "N999"]
"tests/**/*.py" = [
    "S101",    # assert
    "ARG",     # flake8-unused-arguments
    "FBT",     # flake8-boolean-trap
    "PLR2004", # magic-value-comparison
    "S311",    # suspiciuous-non-cryptographic-random-usage
    "SLF001",  # private-member-access
]

[tool.pyright]
exclude = [".venv"]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"

[tool.jupytext.formats]
"notebooks/" = "ipynb"
"scripts/" = "py:percent"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
